### ISSUE TITLE
Get value from an ajax modal onclick

### ISSUE THREAD

**Issue by yangar** [knot-design/MODALite#5]
I m trying to get the value of a row id inside a modal called with Ajax.

I would like to get the row id (data-id) from the modal.

the JavaScript function "onRowClick" is working for the table in the main page but not for the one in the modal.

http://plnkr.co/edit/ehkd8L22KZb0xxCnubUb?p=preview

**Comment by knot-design** [comment]
Here
http://plnkr.co/edit/h9BxxWR9zLjNpr2NQt7d?p=preview

Does it make sense?

**Comment by yangar** [comment]
Yes it's make it! Thank you!

**Comment by knot-design** [comment]
Welcome! Im glad that  I can help you! :D
